In [2]:
import numpy as np


In [3]:
python_list = [1,2,3,4,5]

In [4]:
numpy_array =np.array([1,2,3,4,5])

In [5]:
print(f"Python List: {numpy_array}")


Python List: [1 2 3 4 5]


In [6]:
array = np.zeros(5)

In [7]:
print(f"arrays are {array}")

arrays are [0. 0. 0. 0. 0.]


In [8]:
ones = np.ones(5)

In [9]:
print(f"ones are {ones}")

ones are [1. 1. 1. 1. 1.]


In [10]:
import numpy as np
range =np.arange(0,10,2)

In [11]:
print(f"numpy is{range}")

numpy is[0 2 4 6 8]


In [12]:
random = np.random.randint(8,30,5)

In [13]:
print(f"random numbers are ${random}")

random numbers are $[10 27 10 11 19]


In [14]:
a = np.array([10,11,12,13,14])

In [15]:
b = np.array([1,2,3,4,5])

In [16]:
print(f" sum is ${a+b}")

 sum is $[11 13 15 17 19]


In [17]:
matrix  = np.array(
    [
     [1,2,3],[4,5,6],[7,8,9]

    ]
)

In [18]:
print(f"matrix is ${matrix}")

matrix is $[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print(f"matrix zero is {matrix[0]}")

matrix zero is [1 2 3]


In [20]:
print(f"matrix zero is {matrix[: 0]}")

matrix zero is []


In [21]:
print(f"Shape: {matrix.shape}")
print(f"Size: {matrix.size}")
print(f"Element [0][1]: {matrix[0][1]}")


print(f"First row: {matrix[0]}")
print(f"First column: {matrix[:, 0]}")
print(f"Top-left 2x2: \n{matrix[:2, :2]}")

Shape: (3, 3)
Size: 9
Element [0][1]: 2
First row: [1 2 3]
First column: [1 4 7]
Top-left 2x2: 
[[1 2]
 [4 5]]


In [29]:
reshape =np.arange(1,13)

In [30]:
print(f"Original: {reshape}")

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [31]:
change = reshape.reshape(3,4)

In [32]:
print(f" changed code is ${change}")

 changed code is $[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
flat = change.flatten()

In [37]:
print(f"flat array is {flat}")

flat array is [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
# Cell 5: Dot Product — Linear Algebra (ML ka foundation)
x = np.array([1, 2, 3])
w = np.array([0.5, 0.3, 0.2])  # weights (ML mein model ke weights)

# Dot product = prediction nikalne ka tarika
prediction = np.dot(x, w)  # (1*0.5) + (2*0.3) + (3*0.2) = 1.7
print(f"Input: {x}")
print(f"Weights: {w}")
print(f"Prediction (dot product): {prediction}")

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(f"Matrix multiply:\n{result}")

Input: [1 2 3]
Weights: [0.5 0.3 0.2]
Prediction (dot product): 1.7000000000000002
Matrix multiply:
[[19 22]
 [43 50]]
